site :opscode

cookbook 'apache2', :locked_version => '1.4.2'
cookbook 'build-essential', :locked_version => '1.3.2'
cookbook 'git', :locked_version => '2.1.2'
cookbook 'xml', :locked_version => '1.1.2'

cookbook 'ohai', :git => 'git://github.com/intuit/ohai-cookbook.git' #, :ref => '0.1.0'
cookbook 's3cmd', :git => 'git://github.com/intuit/s3cmd-cookbook.git' #, :ref => '0.1.0'
cookbook 'sudo', :git => 'git://github.com/intuit/sudo-cookbook.git' #, :ref => '0.1.0'
